--
-- PostgreSQL database dump
--

-- Dumped from database version 14.18 (Ubuntu 14.18-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.18 (Ubuntu 14.18-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);




--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);




--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);




--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);




--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);




--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);




--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: canchas_cancha; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.canchas_cancha (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    ubicacion_id bigint NOT NULL
);




--
-- Name: canchas_cancha_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.canchas_cancha ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.canchas_cancha_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cantina_cantina; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.cantina_cantina (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text NOT NULL,
    ubicacion_id bigint NOT NULL
);




--
-- Name: cantina_cantina_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.cantina_cantina ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cantina_cantina_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cantina_marca; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.cantina_marca (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL
);




--
-- Name: cantina_marca_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.cantina_marca ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cantina_marca_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cantina_producto; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.cantina_producto (
    id bigint NOT NULL,
    medida numeric(6,2) NOT NULL,
    nombre character varying(255) NOT NULL,
    unidades_por_bulto integer NOT NULL,
    stock_minimo integer NOT NULL,
    marca_id bigint NOT NULL,
    sabor_id bigint,
    tipo_bulto_id bigint NOT NULL,
    tipo_medida_id bigint NOT NULL,
    tipo_id bigint NOT NULL,
    tipo_unidad_id bigint NOT NULL
);




--
-- Name: cantina_producto_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.cantina_producto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cantina_producto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cantina_productocantina; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.cantina_productocantina (
    id bigint NOT NULL,
    cantidad_en_stock integer NOT NULL,
    precio numeric(6,2) NOT NULL,
    descuento_promocion numeric(6,2) NOT NULL,
    cantina_id bigint NOT NULL,
    producto_id bigint NOT NULL
);




--
-- Name: cantina_productocantina_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.cantina_productocantina ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cantina_productocantina_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cantina_sabor; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.cantina_sabor (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL
);




--
-- Name: cantina_sabor_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.cantina_sabor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cantina_sabor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cantina_tipobulto; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.cantina_tipobulto (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL
);




--
-- Name: cantina_tipobulto_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.cantina_tipobulto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cantina_tipobulto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cantina_tipomedida; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.cantina_tipomedida (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL
);




--
-- Name: cantina_tipomedida_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.cantina_tipomedida ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cantina_tipomedida_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cantina_tipoproducto; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.cantina_tipoproducto (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL
);




--
-- Name: cantina_tipoproducto_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.cantina_tipoproducto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cantina_tipoproducto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cantina_tipounidad; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.cantina_tipounidad (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL
);




--
-- Name: cantina_tipounidad_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.cantina_tipounidad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cantina_tipounidad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: control_caja_billeteencaja; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.control_caja_billeteencaja (
    id bigint NOT NULL,
    denominacion integer NOT NULL,
    cantidad integer NOT NULL,
    ubicacion_id bigint NOT NULL,
    CONSTRAINT control_caja_billeteencaja_cantidad_check CHECK ((cantidad >= 0)),
    CONSTRAINT control_caja_billeteencaja_denominacion_check CHECK ((denominacion >= 0))
);




--
-- Name: control_caja_billeteencaja_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.control_caja_billeteencaja ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.control_caja_billeteencaja_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: control_caja_movimientocajaefectivo; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.control_caja_movimientocajaefectivo (
    id bigint NOT NULL,
    fecha_hora timestamp with time zone NOT NULL,
    total_registrado integer NOT NULL,
    total_real integer NOT NULL,
    total_agregado integer NOT NULL,
    total_final integer NOT NULL,
    detalle_por_billete jsonb NOT NULL,
    diferencia integer NOT NULL,
    observacion character varying(255) NOT NULL,
    ubicacion_id bigint NOT NULL
);




--
-- Name: control_caja_movimientocajaefectivo_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.control_caja_movimientocajaefectivo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.control_caja_movimientocajaefectivo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_cancheroubicacion; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.core_cancheroubicacion (
    id bigint NOT NULL,
    canchero_id integer NOT NULL,
    ubicacion_id bigint NOT NULL
);




--
-- Name: core_cancheroubicacion_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.core_cancheroubicacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_cancheroubicacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);




--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);




--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);




--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);




--
-- Name: finanzas_ajuste; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.finanzas_ajuste (
    id bigint NOT NULL,
    monto numeric(10,2) NOT NULL,
    descripcion text,
    fecha timestamp with time zone NOT NULL,
    caja_efectivo_id bigint,
    caja_transferencia_id bigint
);




--
-- Name: finanzas_ajuste_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.finanzas_ajuste ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.finanzas_ajuste_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: finanzas_cajaefectivo; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.finanzas_cajaefectivo (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    saldo numeric(15,2) NOT NULL,
    correlativo1 character varying(100),
    fecha date NOT NULL,
    ubicacion_id bigint
);




--
-- Name: finanzas_cajaefectivo_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.finanzas_cajaefectivo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.finanzas_cajaefectivo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: finanzas_cajamonedaextranjera; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.finanzas_cajamonedaextranjera (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    saldo numeric(15,2) NOT NULL,
    correlativo1 character varying(100),
    fecha date NOT NULL
);




--
-- Name: finanzas_cajamonedaextranjera_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.finanzas_cajamonedaextranjera ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.finanzas_cajamonedaextranjera_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: finanzas_cajatransferencia; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.finanzas_cajatransferencia (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    saldo numeric(15,2) NOT NULL,
    correlativo1 character varying(100),
    fecha date NOT NULL
);




--
-- Name: finanzas_cajatransferencia_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.finanzas_cajatransferencia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.finanzas_cajatransferencia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: finanzas_categoria; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.finanzas_categoria (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL
);




--
-- Name: finanzas_categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.finanzas_categoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.finanzas_categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: finanzas_etapa; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.finanzas_etapa (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL
);




--
-- Name: finanzas_etapa_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.finanzas_etapa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.finanzas_etapa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: finanzas_gasto; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.finanzas_gasto (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    monto_efectivo numeric(10,2) NOT NULL,
    monto_transferencia numeric(10,2) NOT NULL,
    descripcion text,
    correlativo1 character varying(100),
    correlativo2 character varying(100),
    fecha date NOT NULL,
    automatico boolean NOT NULL,
    caja_efectivo_id bigint,
    caja_transferencia_id bigint,
    categoria_id bigint NOT NULL,
    tipo_id bigint NOT NULL,
    etapa_id bigint,
    ubicacion_id bigint
);




--
-- Name: finanzas_gasto_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.finanzas_gasto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.finanzas_gasto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: finanzas_ingreso; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.finanzas_ingreso (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    monto_efectivo numeric(10,2) NOT NULL,
    monto_transferencia numeric(10,2) NOT NULL,
    descripcion text,
    correlativo1 character varying(100),
    correlativo2 character varying(100),
    fecha date NOT NULL,
    automatico boolean NOT NULL,
    caja_efectivo_id bigint,
    caja_transferencia_id bigint,
    categoria_id bigint NOT NULL,
    tipo_id bigint NOT NULL,
    ubicacion_id bigint
);




--
-- Name: finanzas_ingreso_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.finanzas_ingreso ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.finanzas_ingreso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: finanzas_movimiento; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.finanzas_movimiento (
    id bigint NOT NULL,
    monto numeric(10,2) NOT NULL,
    descripcion text,
    correlativo1 character varying(100),
    fecha date NOT NULL,
    caja_destino_efectivo_id bigint,
    caja_destino_transferencia_id bigint,
    caja_origen_efectivo_id bigint,
    caja_origen_transferencia_id bigint
);




--
-- Name: finanzas_movimiento_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.finanzas_movimiento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.finanzas_movimiento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: finanzas_saldodiario; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.finanzas_saldodiario (
    id bigint NOT NULL,
    fecha date NOT NULL,
    saldo numeric(15,2) NOT NULL,
    caja_efectivo_id bigint,
    caja_moneda_extranjera_id bigint,
    caja_transferencia_id bigint
);




--
-- Name: finanzas_saldodiario_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.finanzas_saldodiario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.finanzas_saldodiario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: finanzas_tipogasto; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.finanzas_tipogasto (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL
);




--
-- Name: finanzas_tipogasto_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.finanzas_tipogasto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.finanzas_tipogasto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: finanzas_tipoingreso; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.finanzas_tipoingreso (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL
);




--
-- Name: finanzas_tipoingreso_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.finanzas_tipoingreso ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.finanzas_tipoingreso_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: finanzas_transaccionme; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.finanzas_transaccionme (
    id bigint NOT NULL,
    tipo_transaccion character varying(10) NOT NULL,
    monto numeric(15,2) NOT NULL,
    tasa_cambio numeric(10,4) NOT NULL,
    fecha date NOT NULL,
    caja_moneda_extranjera_id bigint NOT NULL,
    caja_efectivo_id bigint,
    caja_transferencia_id bigint
);




--
-- Name: finanzas_transaccionme_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.finanzas_transaccionme ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.finanzas_transaccionme_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: jornada_alquiler; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.jornada_alquiler (
    id bigint NOT NULL,
    fecha_hora_inicio timestamp with time zone NOT NULL,
    cliente character varying(100) NOT NULL,
    monto_reserva numeric(8,2),
    monto_alquiler numeric(8,2),
    pagado boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    pago_efectivo numeric(8,2),
    pago_transferencia numeric(8,2),
    comprobantes jsonb,
    cancha_id bigint NOT NULL,
    canchero_id integer,
    jornada_id bigint
);




--
-- Name: jornada_alquiler_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.jornada_alquiler ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jornada_alquiler_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: jornada_gastojornada; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.jornada_gastojornada (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    monto_efectivo numeric(10,2) NOT NULL,
    descripcion text,
    fecha date NOT NULL,
    categoria_id bigint NOT NULL,
    jornada_id bigint NOT NULL,
    tipo_id bigint NOT NULL
);




--
-- Name: jornada_gastojornada_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.jornada_gastojornada ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jornada_gastojornada_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: jornada_jornada; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.jornada_jornada (
    id bigint NOT NULL,
    inicio_jornada timestamp with time zone NOT NULL,
    fin_jornada timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    estado character varying(30) NOT NULL,
    observacion text,
    estado_stock jsonb,
    canchero_id integer NOT NULL,
    cantina_id bigint NOT NULL,
    ubicacion_id bigint NOT NULL,
    diferencia_efectivo numeric(10,2) NOT NULL,
    diferencia_transferencia numeric(10,2) NOT NULL,
    estado_efectivo character varying(20) NOT NULL,
    estado_transferencia character varying(20) NOT NULL
);




--
-- Name: jornada_jornada_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.jornada_jornada ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jornada_jornada_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: jornada_tarearealizada; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.jornada_tarearealizada (
    id bigint NOT NULL,
    fecha_hora_realizacion timestamp with time zone NOT NULL,
    hecha boolean NOT NULL,
    observaciones text,
    canchero_id integer NOT NULL,
    jornada_id bigint NOT NULL,
    tarea_id bigint NOT NULL,
    ubicacion_id bigint NOT NULL
);




--
-- Name: jornada_tarearealizada_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.jornada_tarearealizada ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jornada_tarearealizada_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: jornada_venta; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.jornada_venta (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    fecha_venta timestamp with time zone NOT NULL,
    precio_total numeric(8,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    pago_efectivo numeric(8,2),
    pago_transferencia numeric(8,2),
    aplicar_promocion boolean NOT NULL,
    pagado boolean NOT NULL,
    comprobantes jsonb NOT NULL,
    canchero_id integer NOT NULL,
    jornada_id bigint,
    producto_id bigint NOT NULL
);




--
-- Name: jornada_venta_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.jornada_venta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jornada_venta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservas_excepcionreservafija; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.reservas_excepcionreservafija (
    id bigint NOT NULL,
    fecha date NOT NULL,
    reserva_fija_id bigint NOT NULL
);




--
-- Name: reservas_excepcionreservafija_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.reservas_excepcionreservafija ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservas_excepcionreservafija_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservas_reservaeventual; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.reservas_reservaeventual (
    id bigint NOT NULL,
    fecha date NOT NULL,
    hora_inicio time without time zone NOT NULL,
    duracion numeric(3,1) NOT NULL,
    hora_fin time without time zone NOT NULL,
    cliente character varying(100) NOT NULL,
    monto_senia numeric(10,2),
    cancha_id bigint NOT NULL,
    canchero_id integer NOT NULL,
    ubicacion_id bigint NOT NULL
);




--
-- Name: reservas_reservaeventual_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.reservas_reservaeventual ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservas_reservaeventual_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservas_reservafija; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.reservas_reservafija (
    id bigint NOT NULL,
    fecha_inicio date NOT NULL,
    dia_semana smallint NOT NULL,
    hora_inicio time without time zone NOT NULL,
    duracion numeric(3,1) NOT NULL,
    hora_fin time without time zone NOT NULL,
    cliente character varying(100) NOT NULL,
    monto_senia numeric(10,2),
    cancha_id bigint NOT NULL,
    canchero_id integer NOT NULL,
    ubicacion_id bigint NOT NULL,
    fecha_fin date,
    CONSTRAINT reservas_reservafija_dia_semana_check CHECK ((dia_semana >= 0))
);




--
-- Name: reservas_reservafija_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.reservas_reservafija ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservas_reservafija_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tareas_periodicidad; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.tareas_periodicidad (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL
);




--
-- Name: tareas_periodicidad_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.tareas_periodicidad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tareas_periodicidad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tareas_tarea; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.tareas_tarea (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text,
    horario_aproximado time without time zone,
    periodicidad character varying(10) NOT NULL,
    dia_semana integer,
    dia_mes integer,
    dia_anio date,
    ubicacion_id bigint,
    usuario_id integer,
    habilitada boolean NOT NULL
);




--
-- Name: tareas_tarea_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.tareas_tarea ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tareas_tarea_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ubicacion_ubicacion; Type: TABLE; Schema: public; Owner: cf5
--

CREATE TABLE public.ubicacion_ubicacion (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    direccion character varying(100) NOT NULL,
    ciudad character varying(50) NOT NULL,
    provincia character varying(50) NOT NULL,
    pais character varying(50) NOT NULL,
    celular character varying(20),
    correo character varying(254)
);




--
-- Name: ubicacion_ubicacion_id_seq; Type: SEQUENCE; Schema: public; Owner: cf5
--

ALTER TABLE public.ubicacion_ubicacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ubicacion_ubicacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: cf5
--

COPY public.auth_group (id, name) FROM stdin;
1	propietario
2	canchero
3	tesorero
\.



--
-- Data for Name: tareas_periodicidad; Type: TABLE DATA; Schema: public; Owner: cf5
--

COPY public.tareas_periodicidad (id, nombre) FROM stdin;
\.


--
-- Data for Name: tareas_tarea; Type: TABLE DATA; Schema: public; Owner: cf5
--

COPY public.tareas_tarea (id, nombre, descripcion, horario_aproximado, periodicidad, dia_semana, dia_mes, dia_anio, ubicacion_id, usuario_id, habilitada) FROM stdin;
1	Cepillar cancha	Pasar cepillo. Repartir el caucho de manera uniforme x toda la cancha.	08:30:00	diaria	0	\N	\N	2	3	t
4	Limpiar baños	Baldear, vaciar cestos , tirar perfumina, controlar q todo funcione perfecto.	08:30:00	diaria	0	\N	\N	1	4	t
6	Prender tv	Prender tele ,poner siempre en partidos del día, ir cambiando en hora de los partidos más importantes o lo q pide la gente	15:00:00	diaria	0	\N	\N	\N	\N	t
7	Control perimetral	Redes, tejidos ... Lo q está roto y se puede arreglar se arregla ...lo otro avisar...	08:30:00	diaria	0	\N	\N	\N	\N	t
8	Limpieza mitad d jornada	Limpiar y acomodar afuera d la cancha , barrer nuevamente ,tirar papeles en cesto	20:30:00	diaria	0	\N	\N	\N	\N	t
2	Cepillar cancha	Pasar cepillo, repartiendo uniformemente el caucho x la cancha.	08:30:00	diaria	0	\N	\N	\N	\N	t
3	Limpiar baños	Baldear, vaciar cesto de basura, tirar perfumina, controlar q funcione artefactos perfecto.	08:30:00	diaria	0	\N	\N	\N	\N	t
5	Limpieza y orden afuera d la cancha	Barrer, acomodar mesas, sillas dejar todo presentable y listo para nuestros clientes. Vaciar cestos de basura	08:30:00	diaria	0	\N	\N	\N	\N	t
\.


--
-- Data for Name: ubicacion_ubicacion; Type: TABLE DATA; Schema: public; Owner: cf5
--

COPY public.ubicacion_ubicacion (id, nombre, direccion, ciudad, provincia, pais, celular, correo) FROM stdin;
1	Corrientes	Corrientes 237	Goya	Corrientes	Argentina	\N	\N
2	Huracán	Madariaga 350	Goya	Corrientes	Argentina	\N	\N
3	ClubBanco	Felipe Cabral 2380	Corrientes	Corrientes	Argentina	3795861111	\N
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 3, true);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 158, true);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 176, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 14, true);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 16, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: canchas_cancha_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.canchas_cancha_id_seq', 3, true);


--
-- Name: cantina_cantina_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.cantina_cantina_id_seq', 3, true);


--
-- Name: cantina_marca_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.cantina_marca_id_seq', 26, true);


--
-- Name: cantina_producto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.cantina_producto_id_seq', 56, true);


--
-- Name: cantina_productocantina_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.cantina_productocantina_id_seq', 100, true);


--
-- Name: cantina_sabor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.cantina_sabor_id_seq', 18, true);


--
-- Name: cantina_tipobulto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.cantina_tipobulto_id_seq', 2, true);


--
-- Name: cantina_tipomedida_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.cantina_tipomedida_id_seq', 2, true);


--
-- Name: cantina_tipoproducto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.cantina_tipoproducto_id_seq', 9, true);


--
-- Name: cantina_tipounidad_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.cantina_tipounidad_id_seq', 2, true);


--
-- Name: control_caja_billeteencaja_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.control_caja_billeteencaja_id_seq', 25, true);


--
-- Name: control_caja_movimientocajaefectivo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.control_caja_movimientocajaefectivo_id_seq', 28, true);


--
-- Name: core_cancheroubicacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.core_cancheroubicacion_id_seq', 11, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 42, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 44, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 52, true);


--
-- Name: finanzas_ajuste_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.finanzas_ajuste_id_seq', 7, true);


--
-- Name: finanzas_cajaefectivo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.finanzas_cajaefectivo_id_seq', 3, true);


--
-- Name: finanzas_cajamonedaextranjera_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.finanzas_cajamonedaextranjera_id_seq', 1, true);


--
-- Name: finanzas_cajatransferencia_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.finanzas_cajatransferencia_id_seq', 2, true);


--
-- Name: finanzas_categoria_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.finanzas_categoria_id_seq', 12, true);


--
-- Name: finanzas_etapa_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.finanzas_etapa_id_seq', 2, true);


--
-- Name: finanzas_gasto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.finanzas_gasto_id_seq', 1192, true);


--
-- Name: finanzas_ingreso_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.finanzas_ingreso_id_seq', 937, true);


--
-- Name: finanzas_movimiento_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.finanzas_movimiento_id_seq', 32, true);


--
-- Name: finanzas_saldodiario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.finanzas_saldodiario_id_seq', 1730, true);


--
-- Name: finanzas_tipogasto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.finanzas_tipogasto_id_seq', 10, true);


--
-- Name: finanzas_tipoingreso_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.finanzas_tipoingreso_id_seq', 6, true);


--
-- Name: finanzas_transaccionme_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.finanzas_transaccionme_id_seq', 2, true);


--
-- Name: jornada_alquiler_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.jornada_alquiler_id_seq', 4258, true);


--
-- Name: jornada_gastojornada_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.jornada_gastojornada_id_seq', 461, true);


--
-- Name: jornada_jornada_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.jornada_jornada_id_seq', 892, true);


--
-- Name: jornada_tarearealizada_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.jornada_tarearealizada_id_seq', 2241, true);


--
-- Name: jornada_venta_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.jornada_venta_id_seq', 14198, true);


--
-- Name: reservas_excepcionreservafija_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.reservas_excepcionreservafija_id_seq', 32, true);


--
-- Name: reservas_reservaeventual_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.reservas_reservaeventual_id_seq', 191, true);


--
-- Name: reservas_reservafija_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.reservas_reservafija_id_seq', 111, true);


--
-- Name: tareas_periodicidad_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.tareas_periodicidad_id_seq', 1, false);


--
-- Name: tareas_tarea_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.tareas_tarea_id_seq', 8, true);


--
-- Name: ubicacion_ubicacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: cf5
--

SELECT pg_catalog.setval('public.ubicacion_ubicacion_id_seq', 3, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: canchas_cancha canchas_cancha_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.canchas_cancha
    ADD CONSTRAINT canchas_cancha_pkey PRIMARY KEY (id);


--
-- Name: cantina_cantina cantina_cantina_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.cantina_cantina
    ADD CONSTRAINT cantina_cantina_pkey PRIMARY KEY (id);


--
-- Name: cantina_marca cantina_marca_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.cantina_marca
    ADD CONSTRAINT cantina_marca_pkey PRIMARY KEY (id);


--
-- Name: cantina_producto cantina_producto_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.cantina_producto
    ADD CONSTRAINT cantina_producto_pkey PRIMARY KEY (id);


--
-- Name: cantina_productocantina cantina_productocantina_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.cantina_productocantina
    ADD CONSTRAINT cantina_productocantina_pkey PRIMARY KEY (id);


--
-- Name: cantina_productocantina cantina_productocantina_producto_id_cantina_id_55e48b79_uniq; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.cantina_productocantina
    ADD CONSTRAINT cantina_productocantina_producto_id_cantina_id_55e48b79_uniq UNIQUE (producto_id, cantina_id);


--
-- Name: cantina_sabor cantina_sabor_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.cantina_sabor
    ADD CONSTRAINT cantina_sabor_pkey PRIMARY KEY (id);


--
-- Name: cantina_tipobulto cantina_tipobulto_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.cantina_tipobulto
    ADD CONSTRAINT cantina_tipobulto_pkey PRIMARY KEY (id);


--
-- Name: cantina_tipomedida cantina_tipomedida_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.cantina_tipomedida
    ADD CONSTRAINT cantina_tipomedida_pkey PRIMARY KEY (id);


--
-- Name: cantina_tipoproducto cantina_tipoproducto_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.cantina_tipoproducto
    ADD CONSTRAINT cantina_tipoproducto_pkey PRIMARY KEY (id);


--
-- Name: cantina_tipounidad cantina_tipounidad_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.cantina_tipounidad
    ADD CONSTRAINT cantina_tipounidad_pkey PRIMARY KEY (id);


--
-- Name: control_caja_billeteencaja control_caja_billeteenca_ubicacion_id_denominacio_4ffd9221_uniq; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.control_caja_billeteencaja
    ADD CONSTRAINT control_caja_billeteenca_ubicacion_id_denominacio_4ffd9221_uniq UNIQUE (ubicacion_id, denominacion);


--
-- Name: control_caja_billeteencaja control_caja_billeteencaja_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.control_caja_billeteencaja
    ADD CONSTRAINT control_caja_billeteencaja_pkey PRIMARY KEY (id);


--
-- Name: control_caja_movimientocajaefectivo control_caja_movimientocajaefectivo_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.control_caja_movimientocajaefectivo
    ADD CONSTRAINT control_caja_movimientocajaefectivo_pkey PRIMARY KEY (id);


--
-- Name: core_cancheroubicacion core_cancheroubicacion_canchero_id_ubicacion_id_ec73225d_uniq; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.core_cancheroubicacion
    ADD CONSTRAINT core_cancheroubicacion_canchero_id_ubicacion_id_ec73225d_uniq UNIQUE (canchero_id, ubicacion_id);


--
-- Name: core_cancheroubicacion core_cancheroubicacion_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.core_cancheroubicacion
    ADD CONSTRAINT core_cancheroubicacion_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: finanzas_ajuste finanzas_ajuste_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_ajuste
    ADD CONSTRAINT finanzas_ajuste_pkey PRIMARY KEY (id);


--
-- Name: finanzas_cajaefectivo finanzas_cajaefectivo_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_cajaefectivo
    ADD CONSTRAINT finanzas_cajaefectivo_pkey PRIMARY KEY (id);


--
-- Name: finanzas_cajamonedaextranjera finanzas_cajamonedaextranjera_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_cajamonedaextranjera
    ADD CONSTRAINT finanzas_cajamonedaextranjera_pkey PRIMARY KEY (id);


--
-- Name: finanzas_cajatransferencia finanzas_cajatransferencia_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_cajatransferencia
    ADD CONSTRAINT finanzas_cajatransferencia_pkey PRIMARY KEY (id);


--
-- Name: finanzas_categoria finanzas_categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_categoria
    ADD CONSTRAINT finanzas_categoria_pkey PRIMARY KEY (id);


--
-- Name: finanzas_etapa finanzas_etapa_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_etapa
    ADD CONSTRAINT finanzas_etapa_pkey PRIMARY KEY (id);


--
-- Name: finanzas_gasto finanzas_gasto_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_gasto
    ADD CONSTRAINT finanzas_gasto_pkey PRIMARY KEY (id);


--
-- Name: finanzas_ingreso finanzas_ingreso_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_ingreso
    ADD CONSTRAINT finanzas_ingreso_pkey PRIMARY KEY (id);


--
-- Name: finanzas_movimiento finanzas_movimiento_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_movimiento
    ADD CONSTRAINT finanzas_movimiento_pkey PRIMARY KEY (id);


--
-- Name: finanzas_saldodiario finanzas_saldodiario_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_saldodiario
    ADD CONSTRAINT finanzas_saldodiario_pkey PRIMARY KEY (id);


--
-- Name: finanzas_tipogasto finanzas_tipogasto_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_tipogasto
    ADD CONSTRAINT finanzas_tipogasto_pkey PRIMARY KEY (id);


--
-- Name: finanzas_tipoingreso finanzas_tipoingreso_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_tipoingreso
    ADD CONSTRAINT finanzas_tipoingreso_pkey PRIMARY KEY (id);


--
-- Name: finanzas_transaccionme finanzas_transaccionme_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_transaccionme
    ADD CONSTRAINT finanzas_transaccionme_pkey PRIMARY KEY (id);


--
-- Name: jornada_alquiler jornada_alquiler_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.jornada_alquiler
    ADD CONSTRAINT jornada_alquiler_pkey PRIMARY KEY (id);


--
-- Name: jornada_gastojornada jornada_gastojornada_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.jornada_gastojornada
    ADD CONSTRAINT jornada_gastojornada_pkey PRIMARY KEY (id);


--
-- Name: jornada_jornada jornada_jornada_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.jornada_jornada
    ADD CONSTRAINT jornada_jornada_pkey PRIMARY KEY (id);


--
-- Name: jornada_tarearealizada jornada_tarearealizada_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.jornada_tarearealizada
    ADD CONSTRAINT jornada_tarearealizada_pkey PRIMARY KEY (id);


--
-- Name: jornada_venta jornada_venta_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.jornada_venta
    ADD CONSTRAINT jornada_venta_pkey PRIMARY KEY (id);


--
-- Name: reservas_excepcionreservafija reservas_excepcionreservafija_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.reservas_excepcionreservafija
    ADD CONSTRAINT reservas_excepcionreservafija_pkey PRIMARY KEY (id);


--
-- Name: reservas_reservaeventual reservas_reservaeventual_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.reservas_reservaeventual
    ADD CONSTRAINT reservas_reservaeventual_pkey PRIMARY KEY (id);


--
-- Name: reservas_reservafija reservas_reservafija_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.reservas_reservafija
    ADD CONSTRAINT reservas_reservafija_pkey PRIMARY KEY (id);


--
-- Name: tareas_periodicidad tareas_periodicidad_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.tareas_periodicidad
    ADD CONSTRAINT tareas_periodicidad_pkey PRIMARY KEY (id);


--
-- Name: tareas_tarea tareas_tarea_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.tareas_tarea
    ADD CONSTRAINT tareas_tarea_pkey PRIMARY KEY (id);


--
-- Name: ubicacion_ubicacion ubicacion_ubicacion_pkey; Type: CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.ubicacion_ubicacion
    ADD CONSTRAINT ubicacion_ubicacion_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: canchas_cancha_ubicacion_id_387ab09f; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX canchas_cancha_ubicacion_id_387ab09f ON public.canchas_cancha USING btree (ubicacion_id);


--
-- Name: cantina_cantina_ubicacion_id_d93519bb; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX cantina_cantina_ubicacion_id_d93519bb ON public.cantina_cantina USING btree (ubicacion_id);


--
-- Name: cantina_producto_marca_id_90846666; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX cantina_producto_marca_id_90846666 ON public.cantina_producto USING btree (marca_id);


--
-- Name: cantina_producto_sabor_id_84db2fa1; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX cantina_producto_sabor_id_84db2fa1 ON public.cantina_producto USING btree (sabor_id);


--
-- Name: cantina_producto_tipo_bulto_id_ba4aeaa9; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX cantina_producto_tipo_bulto_id_ba4aeaa9 ON public.cantina_producto USING btree (tipo_bulto_id);


--
-- Name: cantina_producto_tipo_id_d999ae42; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX cantina_producto_tipo_id_d999ae42 ON public.cantina_producto USING btree (tipo_id);


--
-- Name: cantina_producto_tipo_medida_id_1e0e74ee; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX cantina_producto_tipo_medida_id_1e0e74ee ON public.cantina_producto USING btree (tipo_medida_id);


--
-- Name: cantina_producto_tipo_unidad_id_021145f8; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX cantina_producto_tipo_unidad_id_021145f8 ON public.cantina_producto USING btree (tipo_unidad_id);


--
-- Name: cantina_productocantina_cantina_id_350e9d86; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX cantina_productocantina_cantina_id_350e9d86 ON public.cantina_productocantina USING btree (cantina_id);


--
-- Name: cantina_productocantina_producto_id_2eabf409; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX cantina_productocantina_producto_id_2eabf409 ON public.cantina_productocantina USING btree (producto_id);


--
-- Name: control_caja_billeteencaja_ubicacion_id_675392db; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX control_caja_billeteencaja_ubicacion_id_675392db ON public.control_caja_billeteencaja USING btree (ubicacion_id);


--
-- Name: control_caja_movimientocajaefectivo_ubicacion_id_0866ba35; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX control_caja_movimientocajaefectivo_ubicacion_id_0866ba35 ON public.control_caja_movimientocajaefectivo USING btree (ubicacion_id);


--
-- Name: core_cancheroubicacion_canchero_id_1534823c; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX core_cancheroubicacion_canchero_id_1534823c ON public.core_cancheroubicacion USING btree (canchero_id);


--
-- Name: core_cancheroubicacion_ubicacion_id_7353a595; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX core_cancheroubicacion_ubicacion_id_7353a595 ON public.core_cancheroubicacion USING btree (ubicacion_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: finanzas_ajuste_caja_efectivo_id_f7d4afd7; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_ajuste_caja_efectivo_id_f7d4afd7 ON public.finanzas_ajuste USING btree (caja_efectivo_id);


--
-- Name: finanzas_ajuste_caja_transferencia_id_6f56a144; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_ajuste_caja_transferencia_id_6f56a144 ON public.finanzas_ajuste USING btree (caja_transferencia_id);


--
-- Name: finanzas_cajaefectivo_ubicacion_id_3526cae2; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_cajaefectivo_ubicacion_id_3526cae2 ON public.finanzas_cajaefectivo USING btree (ubicacion_id);


--
-- Name: finanzas_gasto_caja_efectivo_id_29986c84; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_gasto_caja_efectivo_id_29986c84 ON public.finanzas_gasto USING btree (caja_efectivo_id);


--
-- Name: finanzas_gasto_caja_transferencia_id_fd9350a5; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_gasto_caja_transferencia_id_fd9350a5 ON public.finanzas_gasto USING btree (caja_transferencia_id);


--
-- Name: finanzas_gasto_categoria_id_9c8a2291; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_gasto_categoria_id_9c8a2291 ON public.finanzas_gasto USING btree (categoria_id);


--
-- Name: finanzas_gasto_etapa_id_d70ece43; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_gasto_etapa_id_d70ece43 ON public.finanzas_gasto USING btree (etapa_id);


--
-- Name: finanzas_gasto_tipo_id_968b55a5; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_gasto_tipo_id_968b55a5 ON public.finanzas_gasto USING btree (tipo_id);


--
-- Name: finanzas_gasto_ubicacion_id_1554417f; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_gasto_ubicacion_id_1554417f ON public.finanzas_gasto USING btree (ubicacion_id);


--
-- Name: finanzas_ingreso_caja_efectivo_id_6e82e5d6; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_ingreso_caja_efectivo_id_6e82e5d6 ON public.finanzas_ingreso USING btree (caja_efectivo_id);


--
-- Name: finanzas_ingreso_caja_transferencia_id_c9746139; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_ingreso_caja_transferencia_id_c9746139 ON public.finanzas_ingreso USING btree (caja_transferencia_id);


--
-- Name: finanzas_ingreso_categoria_id_91deb0ed; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_ingreso_categoria_id_91deb0ed ON public.finanzas_ingreso USING btree (categoria_id);


--
-- Name: finanzas_ingreso_tipo_id_99b4b96d; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_ingreso_tipo_id_99b4b96d ON public.finanzas_ingreso USING btree (tipo_id);


--
-- Name: finanzas_ingreso_ubicacion_id_98c93036; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_ingreso_ubicacion_id_98c93036 ON public.finanzas_ingreso USING btree (ubicacion_id);


--
-- Name: finanzas_movimiento_caja_destino_efectivo_id_6e50bd9c; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_movimiento_caja_destino_efectivo_id_6e50bd9c ON public.finanzas_movimiento USING btree (caja_destino_efectivo_id);


--
-- Name: finanzas_movimiento_caja_destino_transferencia_id_5dfa947a; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_movimiento_caja_destino_transferencia_id_5dfa947a ON public.finanzas_movimiento USING btree (caja_destino_transferencia_id);


--
-- Name: finanzas_movimiento_caja_origen_efectivo_id_c2b52aea; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_movimiento_caja_origen_efectivo_id_c2b52aea ON public.finanzas_movimiento USING btree (caja_origen_efectivo_id);


--
-- Name: finanzas_movimiento_caja_origen_transferencia_id_3d21e115; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_movimiento_caja_origen_transferencia_id_3d21e115 ON public.finanzas_movimiento USING btree (caja_origen_transferencia_id);


--
-- Name: finanzas_saldodiario_caja_efectivo_id_5f09bc08; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_saldodiario_caja_efectivo_id_5f09bc08 ON public.finanzas_saldodiario USING btree (caja_efectivo_id);


--
-- Name: finanzas_saldodiario_caja_moneda_extranjera_id_edea128f; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_saldodiario_caja_moneda_extranjera_id_edea128f ON public.finanzas_saldodiario USING btree (caja_moneda_extranjera_id);


--
-- Name: finanzas_saldodiario_caja_transferencia_id_50c19415; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_saldodiario_caja_transferencia_id_50c19415 ON public.finanzas_saldodiario USING btree (caja_transferencia_id);


--
-- Name: finanzas_transaccionme_caja_destino_id_f27b19fe; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_transaccionme_caja_destino_id_f27b19fe ON public.finanzas_transaccionme USING btree (caja_moneda_extranjera_id);


--
-- Name: finanzas_transaccionme_caja_origen_efectivo_id_3576456d; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_transaccionme_caja_origen_efectivo_id_3576456d ON public.finanzas_transaccionme USING btree (caja_efectivo_id);


--
-- Name: finanzas_transaccionme_caja_origen_transferencia_id_6aba1b40; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX finanzas_transaccionme_caja_origen_transferencia_id_6aba1b40 ON public.finanzas_transaccionme USING btree (caja_transferencia_id);


--
-- Name: jornada_alquiler_cancha_id_9f0aa767; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX jornada_alquiler_cancha_id_9f0aa767 ON public.jornada_alquiler USING btree (cancha_id);


--
-- Name: jornada_alquiler_canchero_id_14911039; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX jornada_alquiler_canchero_id_14911039 ON public.jornada_alquiler USING btree (canchero_id);


--
-- Name: jornada_alquiler_jornada_id_d50926a9; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX jornada_alquiler_jornada_id_d50926a9 ON public.jornada_alquiler USING btree (jornada_id);


--
-- Name: jornada_gastojornada_categoria_id_35629aa1; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX jornada_gastojornada_categoria_id_35629aa1 ON public.jornada_gastojornada USING btree (categoria_id);


--
-- Name: jornada_gastojornada_jornada_id_7de2340a; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX jornada_gastojornada_jornada_id_7de2340a ON public.jornada_gastojornada USING btree (jornada_id);


--
-- Name: jornada_gastojornada_tipo_id_88f578c8; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX jornada_gastojornada_tipo_id_88f578c8 ON public.jornada_gastojornada USING btree (tipo_id);


--
-- Name: jornada_jornada_canchero_id_0ea32c0f; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX jornada_jornada_canchero_id_0ea32c0f ON public.jornada_jornada USING btree (canchero_id);


--
-- Name: jornada_jornada_cantina_id_a87e43f6; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX jornada_jornada_cantina_id_a87e43f6 ON public.jornada_jornada USING btree (cantina_id);


--
-- Name: jornada_jornada_ubicacion_id_dc74a93f; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX jornada_jornada_ubicacion_id_dc74a93f ON public.jornada_jornada USING btree (ubicacion_id);


--
-- Name: jornada_tarearealizada_canchero_id_8075f0b1; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX jornada_tarearealizada_canchero_id_8075f0b1 ON public.jornada_tarearealizada USING btree (canchero_id);


--
-- Name: jornada_tarearealizada_jornada_id_06d26c29; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX jornada_tarearealizada_jornada_id_06d26c29 ON public.jornada_tarearealizada USING btree (jornada_id);


--
-- Name: jornada_tarearealizada_tarea_id_ccf797ad; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX jornada_tarearealizada_tarea_id_ccf797ad ON public.jornada_tarearealizada USING btree (tarea_id);


--
-- Name: jornada_tarearealizada_ubicacion_id_1fb35fe7; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX jornada_tarearealizada_ubicacion_id_1fb35fe7 ON public.jornada_tarearealizada USING btree (ubicacion_id);


--
-- Name: jornada_venta_canchero_id_0d994fc3; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX jornada_venta_canchero_id_0d994fc3 ON public.jornada_venta USING btree (canchero_id);


--
-- Name: jornada_venta_jornada_id_2021b12e; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX jornada_venta_jornada_id_2021b12e ON public.jornada_venta USING btree (jornada_id);


--
-- Name: jornada_venta_producto_id_7b7b5876; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX jornada_venta_producto_id_7b7b5876 ON public.jornada_venta USING btree (producto_id);


--
-- Name: reservas_excepcionreservafija_reserva_fija_id_818dd277; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX reservas_excepcionreservafija_reserva_fija_id_818dd277 ON public.reservas_excepcionreservafija USING btree (reserva_fija_id);


--
-- Name: reservas_reservaeventual_cancha_id_e3ff7060; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX reservas_reservaeventual_cancha_id_e3ff7060 ON public.reservas_reservaeventual USING btree (cancha_id);


--
-- Name: reservas_reservaeventual_canchero_id_05ab776d; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX reservas_reservaeventual_canchero_id_05ab776d ON public.reservas_reservaeventual USING btree (canchero_id);


--
-- Name: reservas_reservaeventual_ubicacion_id_540a0b97; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX reservas_reservaeventual_ubicacion_id_540a0b97 ON public.reservas_reservaeventual USING btree (ubicacion_id);


--
-- Name: reservas_reservafija_cancha_id_e8d8528a; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX reservas_reservafija_cancha_id_e8d8528a ON public.reservas_reservafija USING btree (cancha_id);


--
-- Name: reservas_reservafija_canchero_id_5780d5bd; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX reservas_reservafija_canchero_id_5780d5bd ON public.reservas_reservafija USING btree (canchero_id);


--
-- Name: reservas_reservafija_ubicacion_id_7e8d2b64; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX reservas_reservafija_ubicacion_id_7e8d2b64 ON public.reservas_reservafija USING btree (ubicacion_id);


--
-- Name: tareas_tarea_ubicacion_id_b331f0fb; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX tareas_tarea_ubicacion_id_b331f0fb ON public.tareas_tarea USING btree (ubicacion_id);


--
-- Name: tareas_tarea_usuario_id_02eab1d8; Type: INDEX; Schema: public; Owner: cf5
--

CREATE INDEX tareas_tarea_usuario_id_02eab1d8 ON public.tareas_tarea USING btree (usuario_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: canchas_cancha canchas_cancha_ubicacion_id_387ab09f_fk_ubicacion_ubicacion_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.canchas_cancha
    ADD CONSTRAINT canchas_cancha_ubicacion_id_387ab09f_fk_ubicacion_ubicacion_id FOREIGN KEY (ubicacion_id) REFERENCES public.ubicacion_ubicacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cantina_cantina cantina_cantina_ubicacion_id_d93519bb_fk_ubicacion_ubicacion_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.cantina_cantina
    ADD CONSTRAINT cantina_cantina_ubicacion_id_d93519bb_fk_ubicacion_ubicacion_id FOREIGN KEY (ubicacion_id) REFERENCES public.ubicacion_ubicacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cantina_producto cantina_producto_marca_id_90846666_fk_cantina_marca_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.cantina_producto
    ADD CONSTRAINT cantina_producto_marca_id_90846666_fk_cantina_marca_id FOREIGN KEY (marca_id) REFERENCES public.cantina_marca(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cantina_producto cantina_producto_sabor_id_84db2fa1_fk_cantina_sabor_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.cantina_producto
    ADD CONSTRAINT cantina_producto_sabor_id_84db2fa1_fk_cantina_sabor_id FOREIGN KEY (sabor_id) REFERENCES public.cantina_sabor(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cantina_producto cantina_producto_tipo_bulto_id_ba4aeaa9_fk_cantina_tipobulto_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.cantina_producto
    ADD CONSTRAINT cantina_producto_tipo_bulto_id_ba4aeaa9_fk_cantina_tipobulto_id FOREIGN KEY (tipo_bulto_id) REFERENCES public.cantina_tipobulto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cantina_producto cantina_producto_tipo_id_d999ae42_fk_cantina_tipoproducto_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.cantina_producto
    ADD CONSTRAINT cantina_producto_tipo_id_d999ae42_fk_cantina_tipoproducto_id FOREIGN KEY (tipo_id) REFERENCES public.cantina_tipoproducto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cantina_producto cantina_producto_tipo_medida_id_1e0e74ee_fk_cantina_t; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.cantina_producto
    ADD CONSTRAINT cantina_producto_tipo_medida_id_1e0e74ee_fk_cantina_t FOREIGN KEY (tipo_medida_id) REFERENCES public.cantina_tipomedida(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cantina_producto cantina_producto_tipo_unidad_id_021145f8_fk_cantina_t; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.cantina_producto
    ADD CONSTRAINT cantina_producto_tipo_unidad_id_021145f8_fk_cantina_t FOREIGN KEY (tipo_unidad_id) REFERENCES public.cantina_tipounidad(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cantina_productocantina cantina_productocant_cantina_id_350e9d86_fk_cantina_c; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.cantina_productocantina
    ADD CONSTRAINT cantina_productocant_cantina_id_350e9d86_fk_cantina_c FOREIGN KEY (cantina_id) REFERENCES public.cantina_cantina(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cantina_productocantina cantina_productocant_producto_id_2eabf409_fk_cantina_p; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.cantina_productocantina
    ADD CONSTRAINT cantina_productocant_producto_id_2eabf409_fk_cantina_p FOREIGN KEY (producto_id) REFERENCES public.cantina_producto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: control_caja_billeteencaja control_caja_billete_ubicacion_id_675392db_fk_ubicacion; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.control_caja_billeteencaja
    ADD CONSTRAINT control_caja_billete_ubicacion_id_675392db_fk_ubicacion FOREIGN KEY (ubicacion_id) REFERENCES public.ubicacion_ubicacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: control_caja_movimientocajaefectivo control_caja_movimie_ubicacion_id_0866ba35_fk_ubicacion; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.control_caja_movimientocajaefectivo
    ADD CONSTRAINT control_caja_movimie_ubicacion_id_0866ba35_fk_ubicacion FOREIGN KEY (ubicacion_id) REFERENCES public.ubicacion_ubicacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_cancheroubicacion core_cancheroubicaci_ubicacion_id_7353a595_fk_ubicacion; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.core_cancheroubicacion
    ADD CONSTRAINT core_cancheroubicaci_ubicacion_id_7353a595_fk_ubicacion FOREIGN KEY (ubicacion_id) REFERENCES public.ubicacion_ubicacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: core_cancheroubicacion core_cancheroubicacion_canchero_id_1534823c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.core_cancheroubicacion
    ADD CONSTRAINT core_cancheroubicacion_canchero_id_1534823c_fk_auth_user_id FOREIGN KEY (canchero_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_ajuste finanzas_ajuste_caja_efectivo_id_f7d4afd7_fk_finanzas_; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_ajuste
    ADD CONSTRAINT finanzas_ajuste_caja_efectivo_id_f7d4afd7_fk_finanzas_ FOREIGN KEY (caja_efectivo_id) REFERENCES public.finanzas_cajaefectivo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_ajuste finanzas_ajuste_caja_transferencia_i_6f56a144_fk_finanzas_; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_ajuste
    ADD CONSTRAINT finanzas_ajuste_caja_transferencia_i_6f56a144_fk_finanzas_ FOREIGN KEY (caja_transferencia_id) REFERENCES public.finanzas_cajatransferencia(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_cajaefectivo finanzas_cajaefectiv_ubicacion_id_3526cae2_fk_ubicacion; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_cajaefectivo
    ADD CONSTRAINT finanzas_cajaefectiv_ubicacion_id_3526cae2_fk_ubicacion FOREIGN KEY (ubicacion_id) REFERENCES public.ubicacion_ubicacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_gasto finanzas_gasto_caja_efectivo_id_29986c84_fk_finanzas_; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_gasto
    ADD CONSTRAINT finanzas_gasto_caja_efectivo_id_29986c84_fk_finanzas_ FOREIGN KEY (caja_efectivo_id) REFERENCES public.finanzas_cajaefectivo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_gasto finanzas_gasto_caja_transferencia_i_fd9350a5_fk_finanzas_; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_gasto
    ADD CONSTRAINT finanzas_gasto_caja_transferencia_i_fd9350a5_fk_finanzas_ FOREIGN KEY (caja_transferencia_id) REFERENCES public.finanzas_cajatransferencia(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_gasto finanzas_gasto_categoria_id_9c8a2291_fk_finanzas_categoria_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_gasto
    ADD CONSTRAINT finanzas_gasto_categoria_id_9c8a2291_fk_finanzas_categoria_id FOREIGN KEY (categoria_id) REFERENCES public.finanzas_categoria(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_gasto finanzas_gasto_etapa_id_d70ece43_fk_finanzas_etapa_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_gasto
    ADD CONSTRAINT finanzas_gasto_etapa_id_d70ece43_fk_finanzas_etapa_id FOREIGN KEY (etapa_id) REFERENCES public.finanzas_etapa(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_gasto finanzas_gasto_tipo_id_968b55a5_fk_finanzas_tipogasto_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_gasto
    ADD CONSTRAINT finanzas_gasto_tipo_id_968b55a5_fk_finanzas_tipogasto_id FOREIGN KEY (tipo_id) REFERENCES public.finanzas_tipogasto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_gasto finanzas_gasto_ubicacion_id_1554417f_fk_ubicacion_ubicacion_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_gasto
    ADD CONSTRAINT finanzas_gasto_ubicacion_id_1554417f_fk_ubicacion_ubicacion_id FOREIGN KEY (ubicacion_id) REFERENCES public.ubicacion_ubicacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_ingreso finanzas_ingreso_caja_efectivo_id_6e82e5d6_fk_finanzas_; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_ingreso
    ADD CONSTRAINT finanzas_ingreso_caja_efectivo_id_6e82e5d6_fk_finanzas_ FOREIGN KEY (caja_efectivo_id) REFERENCES public.finanzas_cajaefectivo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_ingreso finanzas_ingreso_caja_transferencia_i_c9746139_fk_finanzas_; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_ingreso
    ADD CONSTRAINT finanzas_ingreso_caja_transferencia_i_c9746139_fk_finanzas_ FOREIGN KEY (caja_transferencia_id) REFERENCES public.finanzas_cajatransferencia(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_ingreso finanzas_ingreso_categoria_id_91deb0ed_fk_finanzas_categoria_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_ingreso
    ADD CONSTRAINT finanzas_ingreso_categoria_id_91deb0ed_fk_finanzas_categoria_id FOREIGN KEY (categoria_id) REFERENCES public.finanzas_categoria(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_ingreso finanzas_ingreso_tipo_id_99b4b96d_fk_finanzas_tipoingreso_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_ingreso
    ADD CONSTRAINT finanzas_ingreso_tipo_id_99b4b96d_fk_finanzas_tipoingreso_id FOREIGN KEY (tipo_id) REFERENCES public.finanzas_tipoingreso(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_ingreso finanzas_ingreso_ubicacion_id_98c93036_fk_ubicacion; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_ingreso
    ADD CONSTRAINT finanzas_ingreso_ubicacion_id_98c93036_fk_ubicacion FOREIGN KEY (ubicacion_id) REFERENCES public.ubicacion_ubicacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_movimiento finanzas_movimiento_caja_destino_efectiv_6e50bd9c_fk_finanzas_; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_movimiento
    ADD CONSTRAINT finanzas_movimiento_caja_destino_efectiv_6e50bd9c_fk_finanzas_ FOREIGN KEY (caja_destino_efectivo_id) REFERENCES public.finanzas_cajaefectivo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_movimiento finanzas_movimiento_caja_destino_transfe_5dfa947a_fk_finanzas_; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_movimiento
    ADD CONSTRAINT finanzas_movimiento_caja_destino_transfe_5dfa947a_fk_finanzas_ FOREIGN KEY (caja_destino_transferencia_id) REFERENCES public.finanzas_cajatransferencia(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_movimiento finanzas_movimiento_caja_origen_efectivo_c2b52aea_fk_finanzas_; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_movimiento
    ADD CONSTRAINT finanzas_movimiento_caja_origen_efectivo_c2b52aea_fk_finanzas_ FOREIGN KEY (caja_origen_efectivo_id) REFERENCES public.finanzas_cajaefectivo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_movimiento finanzas_movimiento_caja_origen_transfer_3d21e115_fk_finanzas_; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_movimiento
    ADD CONSTRAINT finanzas_movimiento_caja_origen_transfer_3d21e115_fk_finanzas_ FOREIGN KEY (caja_origen_transferencia_id) REFERENCES public.finanzas_cajatransferencia(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_saldodiario finanzas_saldodiario_caja_efectivo_id_5f09bc08_fk_finanzas_; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_saldodiario
    ADD CONSTRAINT finanzas_saldodiario_caja_efectivo_id_5f09bc08_fk_finanzas_ FOREIGN KEY (caja_efectivo_id) REFERENCES public.finanzas_cajaefectivo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_saldodiario finanzas_saldodiario_caja_moneda_extranje_edea128f_fk_finanzas_; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_saldodiario
    ADD CONSTRAINT finanzas_saldodiario_caja_moneda_extranje_edea128f_fk_finanzas_ FOREIGN KEY (caja_moneda_extranjera_id) REFERENCES public.finanzas_cajamonedaextranjera(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_saldodiario finanzas_saldodiario_caja_transferencia_i_50c19415_fk_finanzas_; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_saldodiario
    ADD CONSTRAINT finanzas_saldodiario_caja_transferencia_i_50c19415_fk_finanzas_ FOREIGN KEY (caja_transferencia_id) REFERENCES public.finanzas_cajatransferencia(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_transaccionme finanzas_transaccion_caja_efectivo_id_8fac2391_fk_finanzas_; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_transaccionme
    ADD CONSTRAINT finanzas_transaccion_caja_efectivo_id_8fac2391_fk_finanzas_ FOREIGN KEY (caja_efectivo_id) REFERENCES public.finanzas_cajaefectivo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_transaccionme finanzas_transaccion_caja_moneda_extranje_d1486740_fk_finanzas_; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_transaccionme
    ADD CONSTRAINT finanzas_transaccion_caja_moneda_extranje_d1486740_fk_finanzas_ FOREIGN KEY (caja_moneda_extranjera_id) REFERENCES public.finanzas_cajamonedaextranjera(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: finanzas_transaccionme finanzas_transaccion_caja_transferencia_i_3f8d98c8_fk_finanzas_; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.finanzas_transaccionme
    ADD CONSTRAINT finanzas_transaccion_caja_transferencia_i_3f8d98c8_fk_finanzas_ FOREIGN KEY (caja_transferencia_id) REFERENCES public.finanzas_cajatransferencia(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: jornada_alquiler jornada_alquiler_cancha_id_9f0aa767_fk_canchas_cancha_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.jornada_alquiler
    ADD CONSTRAINT jornada_alquiler_cancha_id_9f0aa767_fk_canchas_cancha_id FOREIGN KEY (cancha_id) REFERENCES public.canchas_cancha(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: jornada_alquiler jornada_alquiler_canchero_id_14911039_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.jornada_alquiler
    ADD CONSTRAINT jornada_alquiler_canchero_id_14911039_fk_auth_user_id FOREIGN KEY (canchero_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: jornada_alquiler jornada_alquiler_jornada_id_d50926a9_fk_jornada_jornada_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.jornada_alquiler
    ADD CONSTRAINT jornada_alquiler_jornada_id_d50926a9_fk_jornada_jornada_id FOREIGN KEY (jornada_id) REFERENCES public.jornada_jornada(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: jornada_gastojornada jornada_gastojornada_categoria_id_35629aa1_fk_finanzas_; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.jornada_gastojornada
    ADD CONSTRAINT jornada_gastojornada_categoria_id_35629aa1_fk_finanzas_ FOREIGN KEY (categoria_id) REFERENCES public.finanzas_categoria(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: jornada_gastojornada jornada_gastojornada_jornada_id_7de2340a_fk_jornada_jornada_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.jornada_gastojornada
    ADD CONSTRAINT jornada_gastojornada_jornada_id_7de2340a_fk_jornada_jornada_id FOREIGN KEY (jornada_id) REFERENCES public.jornada_jornada(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: jornada_gastojornada jornada_gastojornada_tipo_id_88f578c8_fk_finanzas_tipogasto_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.jornada_gastojornada
    ADD CONSTRAINT jornada_gastojornada_tipo_id_88f578c8_fk_finanzas_tipogasto_id FOREIGN KEY (tipo_id) REFERENCES public.finanzas_tipogasto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: jornada_jornada jornada_jornada_canchero_id_0ea32c0f_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.jornada_jornada
    ADD CONSTRAINT jornada_jornada_canchero_id_0ea32c0f_fk_auth_user_id FOREIGN KEY (canchero_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: jornada_jornada jornada_jornada_cantina_id_a87e43f6_fk_cantina_cantina_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.jornada_jornada
    ADD CONSTRAINT jornada_jornada_cantina_id_a87e43f6_fk_cantina_cantina_id FOREIGN KEY (cantina_id) REFERENCES public.cantina_cantina(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: jornada_jornada jornada_jornada_ubicacion_id_dc74a93f_fk_ubicacion_ubicacion_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.jornada_jornada
    ADD CONSTRAINT jornada_jornada_ubicacion_id_dc74a93f_fk_ubicacion_ubicacion_id FOREIGN KEY (ubicacion_id) REFERENCES public.ubicacion_ubicacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: jornada_tarearealizada jornada_tarearealiza_jornada_id_06d26c29_fk_jornada_j; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.jornada_tarearealizada
    ADD CONSTRAINT jornada_tarearealiza_jornada_id_06d26c29_fk_jornada_j FOREIGN KEY (jornada_id) REFERENCES public.jornada_jornada(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: jornada_tarearealizada jornada_tarearealiza_ubicacion_id_1fb35fe7_fk_ubicacion; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.jornada_tarearealizada
    ADD CONSTRAINT jornada_tarearealiza_ubicacion_id_1fb35fe7_fk_ubicacion FOREIGN KEY (ubicacion_id) REFERENCES public.ubicacion_ubicacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: jornada_tarearealizada jornada_tarearealizada_canchero_id_8075f0b1_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.jornada_tarearealizada
    ADD CONSTRAINT jornada_tarearealizada_canchero_id_8075f0b1_fk_auth_user_id FOREIGN KEY (canchero_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: jornada_tarearealizada jornada_tarearealizada_tarea_id_ccf797ad_fk_tareas_tarea_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.jornada_tarearealizada
    ADD CONSTRAINT jornada_tarearealizada_tarea_id_ccf797ad_fk_tareas_tarea_id FOREIGN KEY (tarea_id) REFERENCES public.tareas_tarea(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: jornada_venta jornada_venta_canchero_id_0d994fc3_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.jornada_venta
    ADD CONSTRAINT jornada_venta_canchero_id_0d994fc3_fk_auth_user_id FOREIGN KEY (canchero_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: jornada_venta jornada_venta_jornada_id_2021b12e_fk_jornada_jornada_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.jornada_venta
    ADD CONSTRAINT jornada_venta_jornada_id_2021b12e_fk_jornada_jornada_id FOREIGN KEY (jornada_id) REFERENCES public.jornada_jornada(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: jornada_venta jornada_venta_producto_id_7b7b5876_fk_cantina_p; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.jornada_venta
    ADD CONSTRAINT jornada_venta_producto_id_7b7b5876_fk_cantina_p FOREIGN KEY (producto_id) REFERENCES public.cantina_productocantina(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservas_excepcionreservafija reservas_excepcionre_reserva_fija_id_818dd277_fk_reservas_; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.reservas_excepcionreservafija
    ADD CONSTRAINT reservas_excepcionre_reserva_fija_id_818dd277_fk_reservas_ FOREIGN KEY (reserva_fija_id) REFERENCES public.reservas_reservafija(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservas_reservaeventual reservas_reservaeven_cancha_id_e3ff7060_fk_canchas_c; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.reservas_reservaeventual
    ADD CONSTRAINT reservas_reservaeven_cancha_id_e3ff7060_fk_canchas_c FOREIGN KEY (cancha_id) REFERENCES public.canchas_cancha(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservas_reservaeventual reservas_reservaeven_ubicacion_id_540a0b97_fk_ubicacion; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.reservas_reservaeventual
    ADD CONSTRAINT reservas_reservaeven_ubicacion_id_540a0b97_fk_ubicacion FOREIGN KEY (ubicacion_id) REFERENCES public.ubicacion_ubicacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservas_reservaeventual reservas_reservaeventual_canchero_id_05ab776d_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.reservas_reservaeventual
    ADD CONSTRAINT reservas_reservaeventual_canchero_id_05ab776d_fk_auth_user_id FOREIGN KEY (canchero_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservas_reservafija reservas_reservafija_cancha_id_e8d8528a_fk_canchas_cancha_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.reservas_reservafija
    ADD CONSTRAINT reservas_reservafija_cancha_id_e8d8528a_fk_canchas_cancha_id FOREIGN KEY (cancha_id) REFERENCES public.canchas_cancha(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservas_reservafija reservas_reservafija_canchero_id_5780d5bd_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.reservas_reservafija
    ADD CONSTRAINT reservas_reservafija_canchero_id_5780d5bd_fk_auth_user_id FOREIGN KEY (canchero_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: reservas_reservafija reservas_reservafija_ubicacion_id_7e8d2b64_fk_ubicacion; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.reservas_reservafija
    ADD CONSTRAINT reservas_reservafija_ubicacion_id_7e8d2b64_fk_ubicacion FOREIGN KEY (ubicacion_id) REFERENCES public.ubicacion_ubicacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tareas_tarea tareas_tarea_ubicacion_id_b331f0fb_fk_ubicacion_ubicacion_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.tareas_tarea
    ADD CONSTRAINT tareas_tarea_ubicacion_id_b331f0fb_fk_ubicacion_ubicacion_id FOREIGN KEY (ubicacion_id) REFERENCES public.ubicacion_ubicacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tareas_tarea tareas_tarea_usuario_id_02eab1d8_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: cf5
--

ALTER TABLE ONLY public.tareas_tarea
    ADD CONSTRAINT tareas_tarea_usuario_id_02eab1d8_fk_auth_user_id FOREIGN KEY (usuario_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

