version: "3.8"

services:
  ctesf5-db:
    image: postgres:16
    container_name: ctesf5-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
